name: Deploy to Coolify

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: |
          npm run build
          npm run export

      - name: Upload to Coolify (via rsync or SCP)
        run: |
          rsync -avz --delete ./out/ ${{ secrets.COOLIFY_USER }}@${{ secrets.COOLIFY_HOST }}:${{ secrets.COOLIFY_DEPLOY_PATH }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.COOLIFY_SSH_KEY }}
